# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'classifier.ui'
#
# Created: Wed Dec 11 02:16:05 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(442, 380)
        self.svm_groupBox = QtGui.QGroupBox(Dialog)
        self.svm_groupBox.setGeometry(QtCore.QRect(10, 190, 421, 141))
        self.svm_groupBox.setObjectName(_fromUtf8("svm_groupBox"))
        self.kernel_attr_label = QtGui.QLabel(self.svm_groupBox)
        self.kernel_attr_label.setGeometry(QtCore.QRect(10, 70, 107, 16))
        self.kernel_attr_label.setObjectName(_fromUtf8("kernel_attr_label"))
        self.line = QtGui.QFrame(self.svm_groupBox)
        self.line.setGeometry(QtCore.QRect(10, 80, 401, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.layoutWidget = QtGui.QWidget(self.svm_groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 100, 400, 28))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.kcoeff_label = QtGui.QLabel(self.layoutWidget)
        self.kcoeff_label.setObjectName(_fromUtf8("kcoeff_label"))
        self.horizontalLayout_6.addWidget(self.kcoeff_label)
        self.kcoeff_ipt = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.kcoeff_ipt.setEnabled(False)
        self.kcoeff_ipt.setDecimals(1)
        self.kcoeff_ipt.setSingleStep(0.1)
        self.kcoeff_ipt.setObjectName(_fromUtf8("kcoeff_ipt"))
        self.horizontalLayout_6.addWidget(self.kcoeff_ipt)
        self.gridLayout_3.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.kdegree_label = QtGui.QLabel(self.layoutWidget)
        self.kdegree_label.setObjectName(_fromUtf8("kdegree_label"))
        self.horizontalLayout_7.addWidget(self.kdegree_label)
        self.kdegree_ipt = QtGui.QSpinBox(self.layoutWidget)
        self.kdegree_ipt.setEnabled(False)
        self.kdegree_ipt.setProperty("value", 1)
        self.kdegree_ipt.setObjectName(_fromUtf8("kdegree_ipt"))
        self.horizontalLayout_7.addWidget(self.kdegree_ipt)
        self.gridLayout_3.addLayout(self.horizontalLayout_7, 0, 1, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.kgamma_label = QtGui.QLabel(self.layoutWidget)
        self.kgamma_label.setObjectName(_fromUtf8("kgamma_label"))
        self.horizontalLayout_8.addWidget(self.kgamma_label)
        self.kgamma_ipt = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.kgamma_ipt.setDecimals(1)
        self.kgamma_ipt.setSingleStep(0.1)
        self.kgamma_ipt.setObjectName(_fromUtf8("kgamma_ipt"))
        self.horizontalLayout_8.addWidget(self.kgamma_ipt)
        self.gridLayout_3.addLayout(self.horizontalLayout_8, 0, 2, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(self.svm_groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(11, 32, 401, 28))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.kernel_label = QtGui.QLabel(self.layoutWidget1)
        self.kernel_label.setObjectName(_fromUtf8("kernel_label"))
        self.horizontalLayout.addWidget(self.kernel_label)
        self.kernel_ipt = QtGui.QComboBox(self.layoutWidget1)
        self.kernel_ipt.setObjectName(_fromUtf8("kernel_ipt"))
        self.kernel_ipt.addItem(_fromUtf8(""))
        self.kernel_ipt.addItem(_fromUtf8(""))
        self.kernel_ipt.addItem(_fromUtf8(""))
        self.kernel_ipt.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.kernel_ipt)
        self.horizontalLayout.setStretch(0, 10)
        self.horizontalLayout.setStretch(1, 40)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.c_label = QtGui.QLabel(self.layoutWidget1)
        self.c_label.setObjectName(_fromUtf8("c_label"))
        self.horizontalLayout_2.addWidget(self.c_label)
        self.c_ipt = QtGui.QDoubleSpinBox(self.layoutWidget1)
        self.c_ipt.setDecimals(1)
        self.c_ipt.setSingleStep(0.1)
        self.c_ipt.setProperty("value", 1.0)
        self.c_ipt.setObjectName(_fromUtf8("c_ipt"))
        self.horizontalLayout_2.addWidget(self.c_ipt)
        self.horizontalLayout_2.setStretch(0, 10)
        self.horizontalLayout_2.setStretch(1, 40)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.layoutWidget2 = QtGui.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 0, 421, 111))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.roi_ipt = QtGui.QComboBox(self.layoutWidget2)
        self.roi_ipt.setObjectName(_fromUtf8("roi_ipt"))
        self.gridLayout.addWidget(self.roi_ipt, 2, 1, 1, 1)
        self.roi_label = QtGui.QLabel(self.layoutWidget2)
        self.roi_label.setObjectName(_fromUtf8("roi_label"))
        self.gridLayout.addWidget(self.roi_label, 2, 0, 1, 1)
        self.segm_label = QtGui.QLabel(self.layoutWidget2)
        self.segm_label.setObjectName(_fromUtf8("segm_label"))
        self.gridLayout.addWidget(self.segm_label, 1, 0, 1, 1)
        self.input_label = QtGui.QLabel(self.layoutWidget2)
        self.input_label.setObjectName(_fromUtf8("input_label"))
        self.gridLayout.addWidget(self.input_label, 0, 0, 1, 1)
        self.segm_ipt = QtGui.QComboBox(self.layoutWidget2)
        self.segm_ipt.setObjectName(_fromUtf8("segm_ipt"))
        self.gridLayout.addWidget(self.segm_ipt, 1, 1, 1, 1)
        self.input_ipt = QtGui.QComboBox(self.layoutWidget2)
        self.input_ipt.setObjectName(_fromUtf8("input_ipt"))
        self.gridLayout.addWidget(self.input_ipt, 0, 1, 1, 1)
        self.gridLayout.setColumnMinimumWidth(0, 50)
        self.gridLayout.setColumnMinimumWidth(1, 50)
        self.layoutWidget3 = QtGui.QWidget(Dialog)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 120, 421, 61))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.segm_stats_btn = QtGui.QPushButton(self.layoutWidget3)
        self.segm_stats_btn.setObjectName(_fromUtf8("segm_stats_btn"))
        self.horizontalLayout_4.addWidget(self.segm_stats_btn)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.roi_class_field_label = QtGui.QLabel(self.layoutWidget3)
        self.roi_class_field_label.setObjectName(_fromUtf8("roi_class_field_label"))
        self.verticalLayout.addWidget(self.roi_class_field_label)
        self.roi_class_field_ipt = QtGui.QComboBox(self.layoutWidget3)
        self.roi_class_field_ipt.setObjectName(_fromUtf8("roi_class_field_ipt"))
        self.verticalLayout.addWidget(self.roi_class_field_ipt)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.layoutWidget4 = QtGui.QWidget(Dialog)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 340, 421, 32))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.help_btn = QtGui.QPushButton(self.layoutWidget4)
        self.help_btn.setObjectName(_fromUtf8("help_btn"))
        self.horizontalLayout_5.addWidget(self.help_btn)
        self.progressBar = QtGui.QProgressBar(self.layoutWidget4)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout_5.addWidget(self.progressBar)
        self.confirm_buttonBox = QtGui.QDialogButtonBox(self.layoutWidget4)
        self.confirm_buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.confirm_buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.confirm_buttonBox.setObjectName(_fromUtf8("confirm_buttonBox"))
        self.horizontalLayout_5.addWidget(self.confirm_buttonBox)

        self.retranslateUi(Dialog)
        self.kernel_ipt.setCurrentIndex(1)
        QtCore.QObject.connect(self.confirm_buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.confirm_buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.input_ipt, self.input_ipt)
        Dialog.setTabOrder(self.input_ipt, self.segm_ipt)
        Dialog.setTabOrder(self.segm_ipt, self.roi_ipt)
        Dialog.setTabOrder(self.roi_ipt, self.segm_stats_btn)
        Dialog.setTabOrder(self.segm_stats_btn, self.roi_class_field_ipt)
        Dialog.setTabOrder(self.roi_class_field_ipt, self.kernel_ipt)
        Dialog.setTabOrder(self.kernel_ipt, self.c_ipt)
        Dialog.setTabOrder(self.c_ipt, self.kcoeff_ipt)
        Dialog.setTabOrder(self.kcoeff_ipt, self.kdegree_ipt)
        Dialog.setTabOrder(self.kdegree_ipt, self.kgamma_ipt)
        Dialog.setTabOrder(self.kgamma_ipt, self.help_btn)
        Dialog.setTabOrder(self.help_btn, self.confirm_buttonBox)
        Dialog.setTabOrder(self.confirm_buttonBox, self.input_ipt)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Image Classifier", None))
        self.svm_groupBox.setTitle(_translate("Dialog", "SVM Settings", None))
        self.kernel_attr_label.setText(_translate("Dialog", "Kernel Attributes", None))
        self.kcoeff_label.setText(_translate("Dialog", "Coefficient", None))
        self.kdegree_label.setText(_translate("Dialog", "Degree", None))
        self.kgamma_label.setText(_translate("Dialog", "Gamma", None))
        self.kernel_label.setText(_translate("Dialog", "Kernel", None))
        self.kernel_ipt.setItemText(0, _translate("Dialog", "Linear", None))
        self.kernel_ipt.setItemText(1, _translate("Dialog", "RBF", None))
        self.kernel_ipt.setItemText(2, _translate("Dialog", "Poly", None))
        self.kernel_ipt.setItemText(3, _translate("Dialog", "Sigmoid", None))
        self.c_label.setText(_translate("Dialog", "C", None))
        self.roi_label.setText(_translate("Dialog", "ROI Layer", None))
        self.segm_label.setText(_translate("Dialog", "Segmented Image", None))
        self.input_label.setText(_translate("Dialog", "Input Image", None))
        self.segm_stats_btn.setText(_translate("Dialog", "Generate\n"
"Segmented stats", None))
        self.roi_class_field_label.setText(_translate("Dialog", "ROI Class Field", None))
        self.help_btn.setText(_translate("Dialog", "Help", None))

import resource_rc
